Metrics/LineLength:
  Max: 99
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
Documentation:
    Enabled: false
