language: ruby
rvm:
  - 2.2.3
before_install: gem install bundler -v 1.10.6
services:
  - postgresql
before_script:
  - psql -c 'create user "pek-next" with superuser password '\''pek-next'\'';' -U postgres
  - psql -c 'create database "pek-next";' -U postgres
  - psql -c 'create database "pek-next-test";' -U postgres
