env:
  global:
    - CC_TEST_REPORTER_ID=5e2e5d078dc184e654daef9153efc368de5717b4ca7c0de6498b1835004c1ecf
    - GENERATE_TEST_COVERAGE=true
language: ruby
rvm:
  - 2.5.7
before_install: gem install bundler -v 1.10.6
services:
  - postgresql
before_script:
  - psql -c 'create user "pek-next" with superuser password '\''pek-next'\'';' -U postgres
  - psql -c 'create database "pek-next";' -U postgres
  - psql -c 'create database "pek-next-test";' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
  - bundle exec rspec --format doc
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
