version: '2'
services:
  db:
    build: db
    environment:
      - POSTGRES_USER=pek-next
      - POSTGRES_PASSWORD=pek-next
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/pek-next
    ports:
      - "3000:3000"
    depends_on:
      - db
