# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: addcb0773cc6dd0580e79543fade586f31a7b2a5a96cde2a7d0073ffd283e539456750fa3549fc7bab2a0a72f6aa812d9f86196749a1ffed1973df417019968d

test:
  secret_key_base: c794a74f686d1e158a6996413cb3a442fb4427e4ef4073d1b37f9dc5af49b6b523d786b051ac518a68153c5be87df5acbfd6151a7aad840c44a6533dcc0761ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
