apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: data-pvc
spec:
    storageClassName: "standard" # Empty string must be explicitly set otherwise default StorageClass will be set
    volumeName: data-pv
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 50Mi
    